# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: Lib\SigningBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: user_registration }
    app.form.profile:
        class: Lib\SigningBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: user_profile }
    
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
